<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category-list-2</name>
   <tag></tag>
   <elementGuidId>fef02d9a-c8b1-49e4-b076-916bbb065ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-drop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select2-drop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a9dc47d-fe83-4a5e-be78-49dc18a20261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-drop select2-drop-multi select2-display-none select2-drop-active</value>
      <webElementGuid>2c305f60-345d-4094-a028-c363bc89f6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-drop</value>
      <webElementGuid>d65963e2-3c5a-4730-bea9-6197cd658cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness</value>
      <webElementGuid>6f42f77f-fade-4e69-9f18-74386351981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-drop&quot;)</value>
      <webElementGuid>1d94370e-ef20-498a-be79-667299fd6a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='select2-drop']</value>
      <webElementGuid>1f707100-2feb-4502-8779-ff624a1e7176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyElement']/div[9]</value>
      <webElementGuid>f7a39503-09c4-48d8-8229-94b756de2126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-drop', '&quot;', ')')])[1]/following::div[7]</value>
      <webElementGuid>52d2a70f-c47d-47a2-bcd9-3a84201adbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[8]</value>
      <webElementGuid>a6d47598-ec68-4431-aa2d-feb3dc959e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>c40965cd-9d9e-4bc3-8f11-75a058eeac0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'select2-drop' and (text() = '   Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness' or . = '   Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness')]</value>
      <webElementGuid>03bfbf8e-de54-4fb3-8004-f8f1e9934ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
