<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Brand-ul-list</name>
   <tag></tag>
   <elementGuidId>23d7c9a5-aa38-4821-8f02-2f456ea6294e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-drop > ul.select2-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select2-drop']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>e374b017-08f5-4885-b34a-6cf9d85b7e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results</value>
      <webElementGuid>c009723b-1137-4bc0-81c7-664a6cf7a930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerber</value>
      <webElementGuid>b1873729-3039-476d-8c84-260709d2d604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-drop&quot;)/ul[@class=&quot;select2-results&quot;]</value>
      <webElementGuid>64dacc7d-d28a-4c72-94ea-4dedbd9f6ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select2-drop']/ul</value>
      <webElementGuid>ce3afbd8-902b-4d2d-85b6-159aa686ff66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-drop', '&quot;', ')/ul[@class=', '&quot;', 'select2-results', '&quot;', ']')])[1]/following::ul[2]</value>
      <webElementGuid>fff9604b-427b-4c6f-b103-8119f7fcfc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::ul[2]</value>
      <webElementGuid>6e4d3a72-fa4d-4079-98f9-0271ab7fc53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/ul</value>
      <webElementGuid>8718e819-49d9-4d87-ba92-8c8da30a71eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Gerber' or . = 'Gerber')]</value>
      <webElementGuid>9464f502-5bf0-429a-b91d-d9d21a27b3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
