<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No result found_rxLoad</name>
   <tag></tag>
   <elementGuidId>2f4220ba-5eb2-4fd8-959b-92822e446d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rxLoad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rxLoad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61840581-f06d-41be-b3bb-6fb5bbb05a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rxLoad</value>
      <webElementGuid>d9bbb746-cfc4-431d-9d15-b5c3a969069d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rxloadin</value>
      <webElementGuid>d116b70e-7822-4df7-9b94-d3a55523c2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rxLoad&quot;)</value>
      <webElementGuid>795c918b-f7e3-452a-961e-037f5a645f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rxLoad']</value>
      <webElementGuid>c7a05ad9-3d38-4657-b683-b361b526554b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='bodyElement']/div/div[3]</value>
      <webElementGuid>33143dc3-ea1e-49fc-8819-fc24401c278d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No result found.'])[7]/following::div[1]</value>
      <webElementGuid>1894f956-e175-42b8-9a4a-febb1f676cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Trade Date'])[1]/following::div[4]</value>
      <webElementGuid>2346c779-df81-4c0a-b28b-b4cb70ad7926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'rxLoad', '&quot;', ')')])[1]/preceding::div[3]</value>
      <webElementGuid>23f8709c-f120-4c59-acc2-d66c448a5f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>7b0fe674-187c-48ef-af45-3f3663d36f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rxLoad']</value>
      <webElementGuid>ed912da2-826f-4bb7-8fd4-d99f1765e95f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
