<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Category-list</name>
   <tag></tag>
   <elementGuidId>f13d7d40-6c7c-4e63-b9ea-2758082e00bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.select2-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select2-drop']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>650ecc65-ae0d-4599-84e2-013b24edd808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results</value>
      <webElementGuid>811808f8-f3ee-46d1-bfe8-dc1aa62d738c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness</value>
      <webElementGuid>2d6bbc8d-d152-433b-98f8-799864ee1741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-drop&quot;)/ul[@class=&quot;select2-results&quot;]</value>
      <webElementGuid>4799f304-7238-4b74-b6ef-f247c45ad183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select2-drop']/ul</value>
      <webElementGuid>73cdf737-03ba-4964-a61d-2bb003b9be0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-drop', '&quot;', ')/ul[@class=', '&quot;', 'select2-results', '&quot;', ']')])[1]/following::ul[1]</value>
      <webElementGuid>252fd13c-e998-4147-b0cb-cb24b5f0747c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::ul[1]</value>
      <webElementGuid>5e727165-ece2-40c0-87ba-8ba199563570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/ul</value>
      <webElementGuid>20776331-06a9-478c-b927-f0f8472868cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness' or . = 'Baby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness')]</value>
      <webElementGuid>062db00f-5618-4621-abc7-a5ee0049c2ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
