<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profile Photo_uploadImage</name>
   <tag></tag>
   <elementGuidId>d57238a1-ec51-40bf-86da-bc3ad7e69397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b296837-0022-480d-8648-1e08d0412151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadImage</value>
      <webElementGuid>4ea0ead8-1b34-47e9-8cc8-1347f013ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label ng-isolate-scope</value>
      <webElementGuid>1315a555-dd47-44fb-854c-30335bd9d36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>972415e3-3b50-4233-bda8-9bd2ae655d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-event</name>
      <type>Main</type>
      <value>getImageUploaded</value>
      <webElementGuid>cd77f7ae-8b42-4172-88d4-caaca1d0df7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>upload/uploadImage</value>
      <webElementGuid>0ea8ba18-eb5e-4d2b-86d1-1a44e541a805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-object</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>9b38d2de-76c2-4e8b-ae7d-45e1eb2662f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadImage&quot;)</value>
      <webElementGuid>27e1d70b-9242-44bb-a4cb-2aaa4b788fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadImage']</value>
      <webElementGuid>2e5d4a3a-bebb-410f-a9ab-59d7335ada12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div/form/div[3]/div[2]/div[3]/div/input</value>
      <webElementGuid>14405864-298a-46a0-ae74-95e07e3c6791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>d0f96f54-da82-4728-8a1f-2d32c517d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uploadImage' and @type = 'file']</value>
      <webElementGuid>28727de3-292a-438c-9342-b3cd13b4d09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
