<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profile Photo</name>
   <tag></tag>
   <elementGuidId>f190d6ad-c8b4-4aaf-b8e8-4a0535438a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a83d089-f52e-4132-a618-b67613e51795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadImage</value>
      <webElementGuid>8ddf19cb-520a-413f-afd8-c903210b6d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label ng-isolate-scope</value>
      <webElementGuid>7d1284e4-ee4f-40ed-ad18-d8518832f343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8d67d193-951f-4963-bc9e-938fb30bfe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-event</name>
      <type>Main</type>
      <value>getImageUploaded</value>
      <webElementGuid>c0a53618-040b-4673-ac43-9e1bc61173a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>upload/uploadImage</value>
      <webElementGuid>375067b0-a121-45ee-ad10-46028c3ce9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-object</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>d1cb5b16-9ed0-4b49-a7e5-b66933083f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadImage&quot;)</value>
      <webElementGuid>180cd9a5-2877-4d5b-b573-36dc19fc25d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadImage']</value>
      <webElementGuid>294ec8dc-f283-47b3-b89f-d78aa72fbf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div/form/div[3]/div[2]/div[3]/div/input</value>
      <webElementGuid>756037f9-a249-49e0-ae78-8df23c23406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>2304b45a-57d4-4a25-a25f-d49d67e7fae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uploadImage' and @type = 'file']</value>
      <webElementGuid>a28abefa-4025-48fe-97ca-691ef7feae9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
