<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nestle Category Details</name>
   <tag></tag>
   <elementGuidId>dc3a1602-7c33-4d0a-a667-1becdbd39f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.row-hyperlink.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='categoryGrid']/tbody/tr/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38ad87f5-e6be-41f4-bb28-70bafaf6c86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>main-object</name>
      <type>Main</type>
      <value>rxg</value>
      <webElementGuid>d37fdfb1-f1db-4e65-84a1-10cc66102171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>division</value>
      <webElementGuid>e2858c66-fdda-4ca7-a071-78de46d3661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tip-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>cdf8b014-33be-41d9-b901-e6fee01d9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tip-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>b90fb5aa-e7b0-4a49-804e-3612c204cd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>inlineClick(rxg)</value>
      <webElementGuid>c14e7d57-283a-413b-aecf-45a74be3c8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-hyperlink ng-binding</value>
      <webElementGuid>18cdb5ea-be8f-4013-a60b-5aab2101ec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip94024</value>
      <webElementGuid>6837f105-fd31-43b8-837e-da771ddf5bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nestle Category Details </value>
      <webElementGuid>ec274a47-b4e9-4bf1-a535-c6362a19d9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[2]/div[1]/span[@class=&quot;row-hyperlink ng-binding&quot;]</value>
      <webElementGuid>d5853ecf-e009-42c1-96b2-d8ee5b13a9e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='categoryGrid']/tbody/tr/td[2]/div/span</value>
      <webElementGuid>f2501be9-9d00-4b9f-8ec7-24301a096cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::span[1]</value>
      <webElementGuid>7b315404-7749-4bf5-8d86-89324a52f032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::span[2]</value>
      <webElementGuid>dc579018-0b41-4f0e-9b98-c93483128289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nestle Category Details'])[2]/preceding::span[1]</value>
      <webElementGuid>85309a65-dd11-4983-a0ad-d4a81b56ec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atri Kansara'])[1]/preceding::span[2]</value>
      <webElementGuid>0c5cb410-2187-48bb-bdee-cfd1260b22bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nestle Category Details']/parent::*</value>
      <webElementGuid>0d8a8347-ab94-4e3f-8a54-465294dacb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span</value>
      <webElementGuid>a3314ec8-eb73-4a01-ac29-c5f7cda73e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nestle Category Details ' or . = 'Nestle Category Details ')]</value>
      <webElementGuid>95a2f05b-3f5a-4b7a-b1eb-5e2fbebf3beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
