<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category2</name>
   <tag></tag>
   <elementGuidId>9ed9112e-4f71-4d05-8070-b881392192aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[2]/div[2]/div[2]/div/div/div/div/form/div/div/div[9]/div/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe083099-cc0f-4b92-a494-d7884a284e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-invalid-spec.category-detail-id rx-error</value>
      <webElementGuid>b6d620e7-1cf2-4a3b-8b66-46d08bc1b0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spec.categoryDetailId</value>
      <webElementGuid>3c933cab-4d1c-4d5c-83ac-1f16cd6384cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>categoryList.categoryDetailId as categoryList.categoryName  for categoryList  in categoryList</value>
      <webElementGuid>782a213c-987e-4dee-a9b0-40989260183c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getCategoryBrands(spec.categoryDetailId,$index)</value>
      <webElementGuid>ebe0a5d5-dd26-4fb5-bfa9-795ad835a697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>hideBrands</value>
      <webElementGuid>a690622f-711f-486e-b1a0-96f752d9e0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CategoryBaby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness</value>
      <webElementGuid>8b16fd74-5064-48ec-9da7-3a09568d9183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;main ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;wrapper wrapper-content animated fadeInRight&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/form[@class=&quot;form-horizontal ng-pristine ng-invalid ng-invalid-brief.project-name ng-invalid-required ng-invalid-spec.element-name ng-invalid-spec.category-detail-id ng-invalid-spec.brand-id ng-invalid-spec.quantity ng-invalid-spec.unit-class-id ng-invalid-spec.product-type-name&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/div[2]/select[@class=&quot;form-control ng-pristine ng-invalid ng-invalid-spec.category-detail-id rx-error&quot;]</value>
      <webElementGuid>c88a520f-1482-4100-8762-3a51e34eb788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div[2]/div[2]/div/div/div/div/form/div/div/div[9]/div/div/div[2]/select</value>
      <webElementGuid>58feb9aa-636f-41da-a901-d009b0ea11a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Point'])[1]/following::select[1]</value>
      <webElementGuid>c76f166c-97d7-442e-83bd-62eb1671bab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::select[1]</value>
      <webElementGuid>a0df5a32-b644-4db2-bec5-b4fb5f90258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special NotesEg. Artwork Links or Comments'])[1]/preceding::select[4]</value>
      <webElementGuid>e4be2f03-b4bb-4ff5-90d5-bdd2870f4729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[4]</value>
      <webElementGuid>a78fc574-e2f8-4616-b488-eab8a2a925eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3e886576-567f-4b9a-a6b6-77e7e1721009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select CategoryBaby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness' or . = 'Select CategoryBaby FoodsBottled waterCerealsChocolatesCoffeeComplex Cooking AidsConfectioneryCPWCulinary, chilled and frozen foodDairyDeosDressingsDrinksFabric ConditionerFaceFood ServiceGSK DairyHair CareHand &amp; BodyHousehold CareIce CreamIce cream flavorsInfant NutritionLaundryMeal SolutionsNestle Health ScienceNestle ProfessionalOHCPainPet foodPetcarePowder &amp; Liquid BeveragePrepared Dishes &amp; Cooking AidsSkin CleanseSoupsTeaWellness')]</value>
      <webElementGuid>a297a43d-6734-4851-81d9-fbb87fa2b18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
