<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profile Photo_uploadImage</name>
   <tag></tag>
   <elementGuidId>000bce83-806d-4244-a77b-90b502610150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2409a3dc-8df2-4058-8db7-fed3299705e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadImage</value>
      <webElementGuid>e4830a20-8e35-43e1-9767-dfeb7b0b7a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label ng-isolate-scope</value>
      <webElementGuid>2a31d1fb-34b4-409e-9c02-f174be28e94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>5096ac99-282d-40e8-887b-42e758c3973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-event</name>
      <type>Main</type>
      <value>getImageUploaded</value>
      <webElementGuid>e7147a94-a4d1-4971-9afd-e892f48ee219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>upload/uploadImage</value>
      <webElementGuid>91eb7c35-4ece-45e1-b96e-eb7c86d00622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>upload-object</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>17ef3eb6-9a77-4504-af03-fc016da7129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadImage&quot;)</value>
      <webElementGuid>5f028c42-01b4-4f45-976d-72e715e3b73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadImage']</value>
      <webElementGuid>ebc65e94-0b37-4a0c-a4f7-c6b7f8b7a02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div/form/div[3]/div[2]/div[3]/div/input</value>
      <webElementGuid>825c903f-701d-468b-b010-d3e130688f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>014467ae-6213-416f-b8ae-ea2da49440ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uploadImage' and @type = 'file']</value>
      <webElementGuid>28d89452-50ee-45bc-a3d9-fbd3b7e39734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
