<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Brand_select2-choices</name>
   <tag></tag>
   <elementGuidId>74b32303-57bf-454d-a1d0-93c6ec3420c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s2id_autogen5 > ul.select2-choices</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_autogen5']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>db5d0374-e9cc-4411-94d4-52708f4aaa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-choices</value>
      <webElementGuid>94cc0f49-3943-4f43-9bec-1061eb06650b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_autogen5&quot;)/ul[@class=&quot;select2-choices&quot;]</value>
      <webElementGuid>19b8abcb-e4b6-42f4-81af-3f38da012649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_autogen5']/ul</value>
      <webElementGuid>ff093c99-c10b-4bab-9cb3-78f44ea32ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::ul[1]</value>
      <webElementGuid>58679c2a-c321-4d93-8a70-48893034ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bottled water'])[1]/following::ul[1]</value>
      <webElementGuid>e329cceb-3a2c-4eff-99d0-96d3957b6715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Element Details :'])[1]/preceding::ul[2]</value>
      <webElementGuid>704f6c14-14ca-4264-9d09-3cb674c371dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spec Details'])[1]/preceding::ul[2]</value>
      <webElementGuid>d09ebeb7-3b88-4874-8a30-45bb4979ef27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/ul</value>
      <webElementGuid>1b0d84ed-f645-4685-98d3-c949505717a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
