<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Category_select2-choices</name>
   <tag></tag>
   <elementGuidId>e8c4acab-c25d-4375-90c7-a8dfd03222e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.select2-choices</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_autogen3']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>203a2398-650d-4dd3-bdfa-545b70e1fb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-choices</value>
      <webElementGuid>0508d5d7-be5a-4b20-bb47-b15ef08e663b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_autogen3&quot;)/ul[@class=&quot;select2-choices&quot;]</value>
      <webElementGuid>52054fcc-9099-480b-bc92-87151990b4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_autogen3']/ul</value>
      <webElementGuid>fb5954d1-36e8-4ae7-a9e5-a8f9331135b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[2]/following::ul[1]</value>
      <webElementGuid>cdd1977f-dab4-485e-899c-e6aba64c46ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Same Brand'])[1]/following::ul[1]</value>
      <webElementGuid>934a18e9-3444-4573-a5d9-0014b5c43dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/preceding::ul[2]</value>
      <webElementGuid>a1427c77-0453-4f59-bf5f-6dc921bae502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Element Details :'])[1]/preceding::ul[2]</value>
      <webElementGuid>015920eb-c940-4646-98db-781da9c6083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul</value>
      <webElementGuid>295419c7-da69-4d83-9d69-f593d3ffca86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
