<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Product Type3D Aisle WingAisl_5ac5af</name>
   <tag></tag>
   <elementGuidId>091e40c9-18bb-49cd-ae1a-8187a54bd4a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[2]/div[2]/div[2]/div/div/div/div/form/div/div/div[9]/div/div/div[6]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0a3fa455-4b85-402b-8599-dc87714c880a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-invalid-spec.product-type-name rx-error</value>
      <webElementGuid>318dab81-b4e2-423d-b17c-a125c28f4571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spec.productTypeName</value>
      <webElementGuid>5f2a59f7-0741-4308-b8cf-f3ab37355345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>productTypes.productTypeName as productTypes.productTypeName for productTypes  in productTypesList</value>
      <webElementGuid>24686c89-948b-4739-bfdf-67190f33860f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Product Type3D Aisle WingAisle BridgeBasewrapBasket FeederBlitz DisplayBulk DisplayCategory BannersCeramic PotsCladdingConnected EndCounter Top UnitCubesCut Case SleeveDisconnected EndDisplay boxDrop BannerDump Bin (SINGLE)Eye CatcherFlag BannerFloor StandFlyersFree Standing Unit (SINGLE)Fridge BridgeFSU displayGlorifierGondola EndGravity FeederHeader BoardsHot SpotsIn The Run SolutionIsland UnitMaintenanceMason JarsMugPallet SleevePallet WrapPaper CupsParasite UnitParasolPoly-Al FSU CladdingPower WingPromo BoxPull Up BannerReplacement PartShelf DefenderShelf TrayStandeeTable Stand InsertTill WobblersUmbrellaUnit accessoryWall Bay</value>
      <webElementGuid>ca27ad3d-9a39-42f1-9c3d-e976b2ff9b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;main ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;wrapper wrapper-content animated fadeInRight&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/form[@class=&quot;form-horizontal ng-invalid ng-invalid-spec.product-type-name ng-dirty ng-valid-brief.project-name ng-valid-required ng-valid-spec.category-detail-id ng-valid-spec.brand-id ng-valid-spec.element-name ng-valid-spec.quantity ng-valid-spec.unit-class-id&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/div[6]/select[@class=&quot;form-control ng-pristine ng-invalid ng-invalid-spec.product-type-name rx-error&quot;]</value>
      <webElementGuid>4a39c826-da15-44cd-908e-01d760a60c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div[2]/div[2]/div/div/div/div/form/div/div/div[9]/div/div/div[6]/select</value>
      <webElementGuid>38b1d7f2-1975-427a-8694-6e0e02c3455c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Point'])[1]/following::select[4]</value>
      <webElementGuid>d1025eaf-6cde-4a93-8085-edf94665384e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::select[4]</value>
      <webElementGuid>ba277871-83c2-419f-a4bc-bd929e3cf707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special NotesEg. Artwork Links or Comments'])[1]/preceding::select[1]</value>
      <webElementGuid>855a297f-d1df-44ab-9215-d275541d0102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>ae412569-a824-40a6-b588-a243eb592194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>01526dd6-69c3-47d6-8f93-c13877291102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select Product Type3D Aisle WingAisle BridgeBasewrapBasket FeederBlitz DisplayBulk DisplayCategory BannersCeramic PotsCladdingConnected EndCounter Top UnitCubesCut Case SleeveDisconnected EndDisplay boxDrop BannerDump Bin (SINGLE)Eye CatcherFlag BannerFloor StandFlyersFree Standing Unit (SINGLE)Fridge BridgeFSU displayGlorifierGondola EndGravity FeederHeader BoardsHot SpotsIn The Run SolutionIsland UnitMaintenanceMason JarsMugPallet SleevePallet WrapPaper CupsParasite UnitParasolPoly-Al FSU CladdingPower WingPromo BoxPull Up BannerReplacement PartShelf DefenderShelf TrayStandeeTable Stand InsertTill WobblersUmbrellaUnit accessoryWall Bay' or . = 'Select Product Type3D Aisle WingAisle BridgeBasewrapBasket FeederBlitz DisplayBulk DisplayCategory BannersCeramic PotsCladdingConnected EndCounter Top UnitCubesCut Case SleeveDisconnected EndDisplay boxDrop BannerDump Bin (SINGLE)Eye CatcherFlag BannerFloor StandFlyersFree Standing Unit (SINGLE)Fridge BridgeFSU displayGlorifierGondola EndGravity FeederHeader BoardsHot SpotsIn The Run SolutionIsland UnitMaintenanceMason JarsMugPallet SleevePallet WrapPaper CupsParasite UnitParasolPoly-Al FSU CladdingPower WingPromo BoxPull Up BannerReplacement PartShelf DefenderShelf TrayStandeeTable Stand InsertTill WobblersUmbrellaUnit accessoryWall Bay')]</value>
      <webElementGuid>5c2d0d8a-b26f-4209-8d5f-292c141a8978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
