<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProjID</name>
   <tag></tag>
   <elementGuidId>74ce2cf3-ee86-4160-ae00-4f93f30bc519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${ProjID}' or . = '${ProjID}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='projectGrid']/tbody/tr/td[3]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51794be3-80e2-4c00-b40a-4b1a5ae51fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/cHJvamVjdHM00/NDkw</value>
      <webElementGuid>27e044af-166b-40c8-ad0d-5c2f15e839ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>bea2aa20-0c88-4ed5-9850-7468afed6f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${ProjID}</value>
      <webElementGuid>161db1a8-791f-4732-b55a-eedf454127a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[3]/span[1]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>50abe4fd-3365-4948-9a9a-c0d70a42fdbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='projectGrid']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>ba5b4fbd-2f46-4f6d-80ed-02944c17e41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'11820074, Sensodyne 2017 Q1 Campaign')]</value>
      <webElementGuid>117bc1a8-72ef-4fae-b1b4-8bd49b247498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[1]</value>
      <webElementGuid>a83ecf59-294c-4d70-9735-9a88080880d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmed Specs'])[1]/following::a[1]</value>
      <webElementGuid>800e8718-a205-4bd0-8cdf-0e7f0e78478b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>a89e738f-a6d7-4aaf-a430-02fbcd98d287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::a[1]</value>
      <webElementGuid>39bcccc6-0477-4389-957d-dbe67b66fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11820074, Sensodyne 2017 Q1 Campaign']/parent::*</value>
      <webElementGuid>56a48758-315b-481a-ae12-f35c22794063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/cHJvamVjdHM00/NDkw')]</value>
      <webElementGuid>32095286-fd60-4245-8c57-3dd07484ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>6524d3f5-58c1-4448-a34e-a1d7bbf7b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/cHJvamVjdHM00/NDkw' and (text() = '11820074, Sensodyne 2017 Q1 Campaign' or . = '11820074, Sensodyne 2017 Q1 Campaign')]</value>
      <webElementGuid>3d24717e-c26f-4ab9-bb4f-d277ff07e67e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
