<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProjID</name>
   <tag></tag>
   <elementGuidId>74ce2cf3-ee86-4160-ae00-4f93f30bc519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='projectGrid']/tbody/tr/td[3]/span/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${ProjID}' or . = '${ProjID}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da6ca4a1-f805-4af5-94c6-39868994c20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/cHJvamVjdHM00/NDkw</value>
      <webElementGuid>fd497b6a-1620-414b-80a6-4021f1b40342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4384ad29-c7cc-4316-b95b-ac7e2db38691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${ProjID}</value>
      <webElementGuid>baa926f6-71b2-42a7-b0b7-aa768e21a911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[3]/span[1]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>3b6343e4-d1bb-4dd8-8bcc-f3dd74db1188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='projectGrid']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>1ac8a3e7-80c2-41bc-8980-b5f2405f626b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'11820074, Sensodyne 2017 Q1 Campaign')]</value>
      <webElementGuid>d58d97bb-150d-4e7f-99c9-14746b00cba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[1]</value>
      <webElementGuid>ead2ffdb-804a-404c-be9e-a12dd62714d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmed Specs'])[1]/following::a[1]</value>
      <webElementGuid>b4618569-a231-4cde-b1e4-9bc942c9d706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>5c6b89e0-af85-45bb-a205-54a5d99a9603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::a[1]</value>
      <webElementGuid>6dd5aad8-a0a0-417d-8368-2fa39650ab9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11820074, Sensodyne 2017 Q1 Campaign']/parent::*</value>
      <webElementGuid>608cacf7-1cc3-4bc7-a7d0-1862de8981fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/cHJvamVjdHM00/NDkw')]</value>
      <webElementGuid>a95bdd94-b2f6-4053-92e1-ac161d1b9e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>aa1e70e0-cf5f-4336-897b-99a7c5ff56b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/cHJvamVjdHM00/NDkw' and (text() = '11820074, Sensodyne 2017 Q1 Campaign' or . = '11820074, Sensodyne 2017 Q1 Campaign')]</value>
      <webElementGuid>fd356966-45f8-45cd-9d5c-033b4d83eb60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
