<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5017377</name>
   <tag></tag>
   <elementGuidId>dbcdf3f0-7594-4104-8db2-970041d11ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > div > span.row-hyperlink.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='assetProjectGrid']/tbody/tr/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6cc015ce-7879-4c32-83bf-a5e70fc848e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>main-object</name>
      <type>Main</type>
      <value>rxg</value>
      <webElementGuid>341cdb2e-8cfb-48f8-bca1-c329451cb02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>projectNo</value>
      <webElementGuid>634254ad-b896-462d-ab0e-98b79d645cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tip-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>1d58d38f-06ae-420f-9245-0c37ca04cb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tip-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>d3b7a3ca-a66d-4bf7-9f3c-3da2ac87f5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>inlineClick(rxg)</value>
      <webElementGuid>01f4ab97-61c9-48eb-bfd1-42ca0c41f618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-hyperlink ng-binding</value>
      <webElementGuid>ccc94d7c-9446-45f1-bcba-f456703c1eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip680561</value>
      <webElementGuid>016d29ff-80d8-4db6-a0a2-019f1d74b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5017377 </value>
      <webElementGuid>9c317311-3117-4c9c-a05b-d20651e522c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetProjectGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[2]/div[1]/span[@class=&quot;row-hyperlink ng-binding&quot;]</value>
      <webElementGuid>48732459-a36b-462f-99a6-d421d39f4d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='assetProjectGrid']/tbody/tr/td[2]/div/span</value>
      <webElementGuid>35a706c4-c837-4b4f-9afe-f582a18dd4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unilever - SA'])[2]/following::span[1]</value>
      <webElementGuid>97b2bd85-dbcc-49ab-b998-a83a4a2dca48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imported Date'])[1]/following::span[2]</value>
      <webElementGuid>b2585433-1caa-4388-b95c-28de7da34144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ola'])[1]/preceding::span[2]</value>
      <webElementGuid>68c615fd-bc5f-41fe-a85c-ade3d10bf6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5017377']/parent::*</value>
      <webElementGuid>9b741481-856f-4898-a2b5-9f681b85e17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span</value>
      <webElementGuid>02c0ef2c-dd9e-4924-9cef-81c60b6f812c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5017377 ' or . = '5017377 ')]</value>
      <webElementGuid>784b1b35-aa8f-4e81-9ab5-1a12f621da91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
