<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Project</name>
   <tag></tag>
   <elementGuidId>ed7a9880-aed2-41af-a143-ffe24214f816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.number.m-l-lg.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${Project}' or . = '${Project}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8406a63a-0b6a-4a9d-acf3-d3b826781234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number m-l-lg ng-binding</value>
      <webElementGuid>5efbce15-77a0-401f-b54f-e09f4ed4966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>redirectProjectDistribution()</value>
      <webElementGuid>65f639dc-a979-4371-a070-a62b55fa8598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>dashboard.distributedSpec.distributedSpecCount</value>
      <webElementGuid>16600cfe-413d-4f40-8025-f8a6345857d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${Project}</value>
      <webElementGuid>5600cadf-88c2-41dc-9c35-1853de4c9272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;main ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;wrapper wrapper-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 col-md-3&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;number m-l-lg ng-binding&quot;]</value>
      <webElementGuid>0dacc29f-bc94-45c6-8fd3-af0c0b211693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div[2]/div/a</value>
      <webElementGuid>207faae4-5e8d-491a-ab66-e386842459c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2603')]</value>
      <webElementGuid>be17577a-389d-4df8-ad3d-351218c28d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specs in Distribution'])[1]/following::a[1]</value>
      <webElementGuid>12d8c34d-fe8c-4011-b67b-1d25f8d1c7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>dc8053b4-5339-4382-ab40-d1149a1b1f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Damaged Elements'])[1]/preceding::a[1]</value>
      <webElementGuid>88ab81fe-21e3-4133-ae66-240dd6751bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks Assigned to Me'])[1]/preceding::a[2]</value>
      <webElementGuid>9217f2eb-b291-4b98-a32f-c0a1b73da56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2603']/parent::*</value>
      <webElementGuid>254886d3-3465-4863-9bef-09fd58e840cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>c725d9e8-cc39-4be1-b914-6d84a7c55c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '2603' or . = '2603')]</value>
      <webElementGuid>a68da260-853c-4340-aeb9-9731292cce61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
