<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit-button</name>
   <tag></tag>
   <elementGuidId>da613e0f-532c-4f20-8473-2145d6f2ba47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-pencil.cursorPointer.gridIconSpacing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cf26e142-6632-4ced-a04a-1539e874d044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>3e9d17d7-2503-4a3c-b15a-5b709fc80a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>navigateBriefDetail(rxg.projectName)</value>
      <webElementGuid>cf1b6f8a-3dab-4955-a6d9-0254d7fc8703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil cursorPointer gridIconSpacing</value>
      <webElementGuid>948f44ce-482e-49a6-90ee-f20a02650382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brieftemplatesGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[1]/div[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-pencil cursorPointer gridIconSpacing&quot;]</value>
      <webElementGuid>4a0a4d9c-520f-4ada-b99d-f56831e2fb4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/span/i</value>
      <webElementGuid>6ceea574-93ce-4b8f-a31e-bc87ac687bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/span/i</value>
      <webElementGuid>4b744d89-5b70-4295-81d1-ad855e465322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Edit']</value>
      <webElementGuid>28f823e8-0be1-4387-bcb4-ce337d92c591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
