<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>increment_spec details</name>
   <tag></tag>
   <elementGuidId>abe685e4-ce11-4566-8c24-9cb7377b4b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.btn.btn-primary.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div/form/div/div/div[10]/div/div/div[9]/div[2]/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>695e77a1-144b-4f55-b765-6f96cdcfdccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fa fa-plus</value>
      <webElementGuid>d33ef47d-0c4e-4c4d-8a67-0317e6c6210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>isAllowedView == true || $index != 0</value>
      <webElementGuid>cff40879-be96-4180-a0c7-c4055761bb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addNewSpecForEdit()</value>
      <webElementGuid>1bc41e6e-ada8-4e37-b950-ea17df366e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;main ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;wrapper wrapper-content animated fadeInRight&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/form[@class=&quot;form-horizontal ng-valid-brief.project-name ng-valid-required ng-valid-spec.element-name ng-valid-spec.unit-class-id ng-valid-spec.brand-id ng-dirty ng-valid-spec.quantity ng-valid ng-valid-spec.product-type-name&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/div[9]/div[2]/i[@class=&quot;btn btn-primary fa fa-plus&quot;]</value>
      <webElementGuid>75652897-9f8e-4605-9070-16b233426e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[2]/div/div[2]/div/div/div/div/form/div/div/div[10]/div/div/div[9]/div[2]/i[2]</value>
      <webElementGuid>905fc65e-a6a9-4d85-aaa0-19bd3d65d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>88398ae2-2452-4b65-9bae-18b67ea210be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
