<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delet_icon</name>
   <tag></tag>
   <elementGuidId>8f3101c1-a68d-422e-ba83-f92bdf0d9b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash.cursorPointer.gridIconSpacing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a7a6e5aa-8880-45cf-9c56-08331155d967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tip-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>32736aa2-80af-4202-911f-632cae45e15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>events(rxg,&quot;openDeletePopup&quot;)</value>
      <webElementGuid>996c85e5-269d-4094-89a5-5a65e3cf9be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash cursorPointer gridIconSpacing</value>
      <webElementGuid>70f77052-63df-4c5f-9f2d-f57fd5dc31dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>73754184-d469-4c16-8786-0c08f6cd8e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brieftemplatesGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[1]/div[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-trash cursorPointer gridIconSpacing&quot;]</value>
      <webElementGuid>a3d60d04-d227-4973-a2ec-ff721526563a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/span[2]/i</value>
      <webElementGuid>f608c2ce-19b3-4902-8919-ae4f5821b521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>9be74fc4-86eb-4e4f-977e-5b5fd5279e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
