<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_icon</name>
   <tag></tag>
   <elementGuidId>9ec0debc-013e-4260-9cf0-cb0c89486e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-book.cursorPointer.gridIconSpacing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dceefe24-badb-4007-a184-b102e4197b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>b58b7ab5-8d09-479f-a67d-ddd24fac8a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>navigateBriefView(rxg.projectName)</value>
      <webElementGuid>14dcfbbc-813d-41ef-867e-af01e705a091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-book cursorPointer gridIconSpacing</value>
      <webElementGuid>3dc8d8fe-0c1d-4bac-9def-64bbb8de336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brieftemplatesGrid&quot;)/tbody[1]/tr[@class=&quot;undefined ng-scope&quot;]/td[1]/div[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-book cursorPointer gridIconSpacing&quot;]</value>
      <webElementGuid>a52fb0d2-6f16-437c-a355-8819c2f11ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='brieftemplatesGrid']/tbody/tr/td/div/i</value>
      <webElementGuid>8ef60ec3-cec5-4178-ac03-207819b030e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/i</value>
      <webElementGuid>ce808fcc-4027-46da-a2a5-f5688bdbe29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'View']</value>
      <webElementGuid>1956953a-297a-47ca-9392-f0bd23dd9cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
